### ISSUE TITLE
Fix up the Shoes console

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1321]
Realized another gap with Shoes 3, and that's the old console. It could be brought up with a simple `Alt+/`, and provided visibility to the errors and output that happened in your Shoes app.

![image](https://cloud.githubusercontent.com/assets/130504/21001024/e6cd06d2-bcd2-11e6-8a3e-3111a1b1ce62.png)

Personally spitting problems to STDOUT matches my expectation, but these aren't necessarily exclusive. We could easily spot errors in block evaluations, and write to both locations.

If we intend to have a "Shoes" app like old Shoes shipped (maybe related to #125?), where people might be starting from OS app launchers instead of a terminal, the console might be a necessity to see when things go side-ways. Or perhaps there's a better/different paradigm we could do to help, especially beginners, when their apps hit an error.

What do y'all think❓❔❓

## TODO

* [x] Fix so logging works
* [x] Ensure (or fix?) so exceptions get written. Don't break writing to STDOUT too!
* [x] Better notification scheme for updates than polling

**Comment by ccoupe** [comment]
I use both in Shoes 3. The console, log.rb, alt-/ to find the Ruby/Shoes syntax problems and also debugging puts in the code - none of those ruby puts will be seen if Shoes is launched as an app where stdout, stderr, and stdin are effectively /dev/null. The next Shoes 3 (3.3.2) has a Shoes.terminal that can be called if the end user really wants it and it redirects GUI launched stdin/out/err to it. Pain in the native ass. Lot's of C and Objective-C. But you can run things like mini-tests  and some other low level thing creatures from Shoes 3.3.2 and get color highlighting.

The debug,info,warn methods are part of Shoes "classic" and they go to log.rb (pure ruby, last I looked)

**Comment by PragTob** [comment]
But... we have the shoes console already or what am I missing? Ever since 2013 afaik. Maybe the keyboard short cut is broken on mac but on Linux it works fine. It's [here](https://github.com/shoes/shoes4/blob/master/shoes-core/lib/shoes/logger.rb) - maybe some of the recent rubocop fixes broke it? Those are the last commits.

Meaning, it opens... now when I tried it out it seems to be broken, e.g. the log does not update when I call methods. I'll PR a simple sample. 

The implementation also needs some love, it's one of those slightly evil things that uses a constant to put data in `Shoes::LOG` - that should be switched to a class side instance variable or even better in an object so that different shoes app windows have different logs. And then it updates every 0.2 seconds - maybe some event notification connection might be better.

**Comment by PragTob** [comment]
For further reference, first implementation was in #374 and the original issue discussion is #194 - iirc we made it so that it is always also printed out on the CLI (which works for me atm) which is a good thing imo :)

**Comment by jasonrclark** [comment]
Thanks @ccoupe! Always good to hear about how other folks are using things.

@PragTob Ah, I think hit the shortcut key, then briefly I grepped (late at night 😴 ) for `console`, hence why I didn't find it. Thanks for shedding light there.

I've updated the title and added a TODO list in the body so we can track some of the various tasks around getting the console back to 👌

**Comment by jasonrclark** [comment]
Started digging into this and realized we need to decide on #619 before we can really land the console. Basically, in Shoes 4 right now, you'd **never ever** see one of these exceptions on the console, because the whole app bails.

In #619 @PragTob expressed 1) disfavor for the rescue-and-carry-on feature as a user and 2) concern about monkey-patching required. I'm sympathetic to that viewpoint, but after more thought it feels like a huge compatibility break to change this behavior.

Given that, I'd propose on 1) that we add an ENV var/command-line flag (`SHOES_FAIL_HARD`, `--fail-hard` or something?) which when set uses our let-it-crash philosophy. I know I'd set that in my local ENV in a heartbeat and keep things how they are, but let upgrading users get what they had before.

On 2) I'm not convinced this would need anything too invasive. Everything in Shoes executes inside of a block we're explicitly triggering ourselves (or have a wrapper around), whether in the [app](https://github.com/shoes/shoes4/blob/736702e375d7a1e7886a9d77a1add785ca0677b4/shoes-core/lib/shoes/app.rb#L93), [internal app](https://github.com/shoes/shoes4/blob/736702e375d7a1e7886a9d77a1add785ca0677b4/shoes-core/lib/shoes/internal_app.rb#L136), [click handlers](https://github.com/shoes/shoes4/blob/ddcb039935540a847538d8b74b4893182e6b924d/shoes-swt/lib/shoes/swt/click_listener.rb#L59-L67) or elsewhere. While it's a bit tedious, I believe simply rescuing and logging at each of these points gives us the same behavior Shoes 3 had... is there something else I'm missing?

**Comment by PragTob** [comment]
I think the monkey patching part of the comment of past self  to `"string".touch` - capturing in general should be okay to do just at top level where we start the app block I guess.

I'm still in favor of crashing hard, as I firmly believe it's the better behaviour and better experience (in shoes 3 I often wondered "uh why isn't that showing/happening" and rememberd too late to check the shoes console for errors).

That said, I get the compatibility argument although I think that in important points it's ok to break it. If you feel strongly with it I'm ok for rolling with it as well :)

**Comment by jasonrclark** [comment]
Another point alongside the compatibility is what happens in packaged apps where you don't necessarily end up getting STDOUT. For those type of apps, a crash would simply have the app disappear which would be seriously 😭 

My plan at this point is to do the wrappers, add optional fail-fast, and put in for a later release to potentially flop the default (with some provision for packaged stuff). Cool enough @PragTob?

**Comment by PragTob** [comment]
Great :rocket:

**Comment by jasonrclark** [comment]
Entered #1411 and got the #1409 running to put fail fast in, so I'm gonna close this out.
