### ISSUE TITLE
Split up `shoes-core/lib/shoes/dsl.rb`

### ISSUE THREAD

**Issue by jasonrclark** [shoes/shoes4#1341]
Per https://github.com/shoes/shoes4/pull/1336#discussion_r93190641, this file has gotten pretty long. A sensible way of breaking it up would be 💯 .

**Comment by OrthoDex** [comment]
Hi!

I would like to take this up if it's alright. :smile: 

Code Climate shows the duplication and complexity, and I understand that the DSL could be sliced up into Art, TextBlock etc according to @PragTob

**Comment by PragTob** [comment]
Hi there @OrthoDex !

Thanks for wanting to help! Yes it should, although I'm not entirely sure on all the categories yet. Art/TextBlock seem sensible but there is other stuff, e.g. Timer related things.

Before you get all started in code I think it might be a good thing to have a look at the methods (I don't have that much tome atm) and see what these and the other categories could be so that we could talk about them at least a bit before we mold them into code.

What do you think? :)

**Comment by OrthoDex** [comment]
On it @PragTob ! :smiley: 

I'll try and propose a splitup into specific modules after going through the methods.

**Comment by OrthoDex** [comment]
Hi @PragTob ,

I went through the code and I could roughly identify a few potential groupings. These are based on the broad functionality they provide. The code comments helped out a **lot**, since I could identify the parts providing diff functionalities.

Here it goes:

- DSL::Setup (including DeprecatedShoesGemSetup, #load_backend, #setup )
- DSL::Style (housing all private methods for style_* apart from #create)
- DSL::Element (housing all major elements along with #create
- DSL::Animate (Not sure about this, since organizing #timer and #sound together doesn't sound like good practice, no pun intended.)
- DSL::Art or DSL::Shape (to include Shoes::Arrow, Shoes::Arc till Shoes::Star)
- DSL::AppStyle (for TextStyle, PATTERN_APP_STYLES and OTHER_APP_STYLES)
- DSL::Action (for mouse and key related actions like #hover, #scroll_top, #download etc)

What do you think?

**Comment by PragTob** [comment]
Hey there!

Looks roughly good to me, couple of comments.

* load_backend/setup are class methods, e.g. not like the rest of the flock, they could still move to a module but would probably keep them out of the DSL namespace
* DSL::Style/style_* methods is indeed more private and not meant for "normal" users to call - I think this will end up as a module that is included in some other DSL modules. However, we might even find out that some methods are just called from some modules (if slices right) so they could just be put as private in there
* DSL::Element - not sure what you mean with major/elements 0 what should go in here
* DSL::Animate - I guess timer/animate/every can go in here but not sound that sounds weird... although maybe it should be called "Timing" or something like that then? Naming is hard!
* DSL::Art - that sounds right :)
* DSL::AppStyle - I think the text styles should live with the text methods, e.g. I think I'm missing a DSL::Text (or TextBlock) for all the Text related stuff). For the others, AppStyles sounds sort of alright
* DSL::Action - maybe sound can over here together with download? And maybe keystrokes and mouse stuff can go into an Input module? I'm not quite sure.


So hope what I wrote helps. Would like @jasonrclark to give this a look as well :)

Thanks for the work!
Tobi

**Comment by jasonrclark** [comment]
Agreed that this is looking like a good start! I'll only mention things that I have something to say about... all the others are 👌 as a plan:

* With the `load_backend/setup`, I'd definitely consider moving the code, but with the class methods I wouldn't try too hard to extract them into a separate module. Just open `Shoes` like it does and add them... class methods added via other modules are kind of a mess to get right.
* DSL::Element -- I interpreted this as "all the non-art elements" like `button`, `edit_line`, etc. Is that your intent @OrthoDex?
* DSL::Animate -- I feel like `Timing` makes me think that it'll be doing benchmarking or something... actually favor either `Animate` or maybe `Timer` (after one of the actual methods?) but they're a bit hard to categorize.
* DSL::AppStyle -- are there app-level things that aren't necessarily styling related that might incline this toward `DSL::App` instead? I'm thinking stuff like `gutter` and `clipboard`.
* DSL::Text -- Totally 👍 on having a separate breakout for text methods.
* DSL::Action -- Not stuck on it, but could this be `DSL::Interaction` or `DSL::Input` if it's primarily about keyboard/mouse stuff that happens?

Anyway, this definitely looks good enough to get started on! I'd recommend two things 1) do a single extraction per commit (we like lots of small commits) and 2) open a PR as soon as you have one or two, and I'd be happy to look over them. Generally I'm looking over stuff evening Pacific time, and I'll try to get you feedback as quickly as possible.

Thanks again for reaching out to get involved! ✨

**Comment by PragTob** [comment]
:+1: I like `DSL::Interaction` or Inpt.

I often look over stuff ~9am Central European Time (aka right now) and if I'm not out too later some time between 7pm and 10pm Central European Time. :)

**Comment by OrthoDex** [comment]
> DSL::Element -- I interpreted this as "all the non-art elements" like button, edit_line, etc.
Yep!
Sorry about not being clear enough.

I'll issue a PR for one extraction soon!

**Comment by OrthoDex** [comment]
Issued a PR for the text module at #1391 .

**Comment by PragTob** [comment]
Thanks for all the work! :+1:

**Comment by OrthoDex** [comment]
Creating a list to keep track of changes:

- [X] DSL::Text - Merged in #1391 
- [X] DSL::Art - Merged in #1396 
- [X] DSL::Interaction - Merged in #1395 
- [] DSL::Element
- [] DSL::ElementStyle

Couple of things:

1. DSL::ElementStyle seems more appropriate than AppStyle (since there is #style_for_element, #normalize_style_for_element etc).
2. DSL::Media could hold #video and #sound.

What do you think @PragTob @jasonrclark

**Comment by PragTob** [comment]
DSL::Media sounds good, ElementStule sounds good on a first thought need to see the PR to be certain though :)

**Comment by OrthoDex** [comment]
yeah, I'll move image to media :smile:

**Comment by OrthoDex** [comment]
Hey @jasonrclark , @PragTob !
I was able to finish the animate extraction as well this weekend. As soon as #1398 is merged, I'll issue another PR and that should hopefully cover all the extractions. :smile: 

On a side note, code climate doesn't reflect the changes made to the codebase. Is it set to analyse per release?

**Comment by PragTob** [comment]
No idea what's up with code climate, it doesn't seem to have updated in a month... somethings seems wrong. Gnargh.

**Comment by OrthoDex** [comment]
Hey @PragTob @jasonrclark ,
Is there anything else left to do?

**Comment by PragTob** [comment]
No, I don't think so. Thank you a lot for your work and dedication :tada: :rocket:

**Comment by jasonrclark** [comment]
Agreed! Great work on this @OrthoDex.
