### ISSUE TITLE
Split shoes into a meta-gem and sub-gems

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#688]
Before we release 4.0.0, we should stabilize the boundaries between code layers. Based on previous conversation, this would include at least
- shoes-dsl: the DSL layer
- shoes-swt: the SWT backend

I would imagine that the "shoes" gem would be a meta-gem that includes the two above.
- [ ] Figure out a strategy for sharing DSL specs with the backend. Perhaps [git subtree](http://makingsoftware.wordpress.com/2013/02/16/using-git-subtrees-for-repository-separation/)
- [ ] Develop a workflow for keeping gems synced during development
- [ ] Develop a workflow for keeping gem releases synced
