### ISSUE TITLE
Style meta issues tasklist

### ISSUE THREAD

**Issue by KCErb** [shoes/shoes4#711]
When PR #683 lands it will have some issues. Those are documented here to remind us to figure them out, without delaying an already very bloated little PR. :)
- [x] Rename `clickable_opts` since we're in the process of changing `opts` to `styles`
- [x] Create a good "complete" set of  `STYLE_GROUPS` and comment on them. The style groups will overlap in content since there is so little natural overlap in the styles. For example, both text and art (oval, rect, etc) use the `:click` style. So a text item could style with `text_styles` and an art item will style with `art_styles` and both would contain the `:click` style.
- [x] Try to minimize duplication in specs. Right now style specs has a list of `all_the_styles` but maybe that list should be created by `STYLE_GROUPS.flatten.flatten.uniq`. What's more is that (for now) when writing specs for an element (take arc for an example) we need to list out the styles (on the style list_ that it styles with. We'd prefer to use `Shoes::Arc.supported_styles` but that would return styles like `:wedge:` or `angle1` which is not on the standard styles list. 
- [x] Get rid of an app-level `:fill` default. Right now it is black, but many elements (text for example) should not default to black. 
- [x] Apply the new way to handle styles to all elements!
  - ~~Arrow~~ (arrow's not implemented yet)
  - [x] Arc
  - [x] Background
  - [x] Border 
  - [x] Button
  - [x] Check
  - [x] Edit Line and Edit Box (input_box)
  - [x] Flow (via Slot)
  - ~~Gradient~~ (not a real element)
  - [x] Image
  - [x] Line
  - [x] Link (via Span via TextBlock?) 
  - [x] ListBox
  - ~~Mask~~ (not implemented yet)
  - [x] Oval
  - ~~Point~~ (not a real element)
  - [x] Progress
  - [x] Radio
  - [x] Rect
  - [x] Shape
  - [x] Stack (via Slot)
  - [x] Star
  - [x] TextBlock / Text (para, banner, span, sub, strong, tagline etc. . .)
  - ~~Widget~~ (not a real element)
- [x] Add transform and translate to list of dsl-level art methods
- [x] Add `release` as a style to elements that support click
- [x] Move `style_init` to precede dimensions and then hand the style hash to dimensions, and in general try to clean up / make uniform the implementation of style since it was done over multiple PRs.

I believe that's all of them. Please let me know if I should add to this list. Or if some of these belong in their own independent issue.
